version: '3'

services:
  db:
    image: postgres:alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
  web:
    build: ./portional-web/
    ports:
      - '8000:8000'
    depends_on:
      - db

volumes:
  postgres-data:
